filter:
    excluded_paths: [ 'vendor/*', 'tests/*', 'samples/*', 'src/PhpWord/Shared/PCLZip/*' ]

before_commands:
    - "composer install --prefer-source --dev"

tools:
    external_code_coverage:
        enabled: true
        timeout: 900
    php_sim:
        min_mass: 25
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
